[env:watch]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.flash_size = 32MB
board_build.psram_type = opi

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -I include

lib_deps =
    https://github.com/moononournation/Arduino_GFX.git
    lewisxhe/XPowersLib
    lvgl/lvgl@9.3.0